"""empty message

Revision ID: 393f7fdff5e3
Revises: d51ff521a779
Create Date: 2021-01-27 23:39:36.826806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393f7fdff5e3'
down_revision = 'd51ff521a779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('Venue', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'image_link')
    # ### end Alembic commands ###
